# Generated by Django 3.0.5 on 2020-04-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=30, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
