# Generated by Django 3.0.5 on 2020-04-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=30, null=True)),
                ('student_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='card_id',
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('card_id', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('access', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.User')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.Access'),
        ),
    ]
