# Generated by Django 3.0.5 on 2020-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200425_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='registred_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
