# Generated by Django 3.0.5 on 2020-04-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_access_registred_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=30, null=True)),
                ('device_ip', models.CharField(max_length=30, null=True)),
                ('device_model', models.CharField(max_length=30, null=True)),
                ('check_out', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(choices=[('en', 'en'), ('kz', 'kz'), ('ru', 'ru')], default='en', max_length=30, null=True)),
                ('position', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=30, null=True)),
                ('student_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('advisor', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.Employees'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
