# Generated by Django 3.0.5 on 2020-04-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20200425_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_ip', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=30, null=True)),
                ('device_model', models.CharField(max_length=30, null=True)),
                ('is_out', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=30, null=True)),
                ('check_out', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
        migrations.RemoveField(
            model_name='history',
            name='status',
        ),
        migrations.AddField(
            model_name='history',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.Device'),
        ),
    ]
