# Generated by Django 3.0.5 on 2020-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20200425_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='wait_time',
            field=models.IntegerField(default=2),
        ),
    ]
